services:
  ds_system.service.identities.tenant:
    parent: ds_system.service
    class: '%ds_system.service.identities.tenant.class%'
    tags:
      - { name: ds_system.service, alias: identities.tenant }
