parameters:
    ds_model.event_listener.identitiable.class: Ds\Component\Model\EventListener\IdentitiableListener
    ds_model.event_listener.uuidentifiable.class: Ds\Component\Model\EventListener\UuidentifiableListener
    ds_model.event_listener.translatable.class: Ds\Component\Model\EventListener\TranslatableListener
    ds_model.event_listener.localizable.class: Ds\Component\Model\EventListener\LocalizableListener

services:
    ds_model.event_listener.identitiable:
        class: '%ds_model.event_listener.identitiable.class%'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ds_model.event_listener.uuidentifiable:
        class: '%ds_model.event_listener.uuidentifiable.class%'
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    ds_model.event_listener.translatable:
        class: '%ds_model.event_listener.translatable.class%'
        arguments:
            - '@annotation_reader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    ds_model.event_listener.localizable:
        class: '%ds_model.event_listener.localizable.class%'
        arguments:
            - '@annotation_reader'
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: kernelView, priority: 17 }
