services:
  ds_security.doctrine.orm.query_extension.enabled:
    class: '%ds_security.doctrine.orm.query_extension.enabled.class%'
    public: false
    arguments:
      - '@security.token_storage'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
      - { name: api_platform.doctrine.orm.query_extension.item }

  ds_security.doctrine.orm.query_extension.deleted:
    class: '%ds_security.doctrine.orm.query_extension.deleted.class%'
    public: false
    arguments:
      - '@request_stack'
      - '@security.token_storage'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
      - { name: api_platform.doctrine.orm.query_extension.item }

  ds_security.doctrine.orm.query_extension.permission.entity:
    class: '%ds_security.doctrine.orm.query_extension.permission.entity.class%'
    public: false
    arguments:
      - '@security.token_storage'
      - '@ds_security.service.access'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
