services:
  ds_security.resolver.context.identity.persona:
    class: '%ds_security.resolver.context.identity.persona.class%'
    arguments:
      - '@security.token_storage'
      - '@ds_api.api'
    tags:
      - { name: ds_resolver.resolver, alias: ds.context.identity.persona }

  ds_security.resolver.context.identity:
    class: '%ds_security.resolver.context.identity.class%'
    arguments:
      - '@security.token_storage'
      - '@ds_api.api'
    tags:
      - { name: ds_resolver.resolver, alias: ds.context.identity }
