services:
  ds_security.tenant.unloader.access:
    class: '%ds_security.tenant.unloader.access.class%'
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader }


  ds_security.tenant.unloader.permission:
    class: '%ds_security.tenant.unloader.permission.class%'
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader, priority: -1 }
