services:
  ds_encryption.service.cipher:
    class: '%ds_encryption.service.cipher.class%'
    arguments:
      - '%encryption%'

  ds_encryption.service.encryption:
    class: '%ds_encryption.service.encryption.class%'
    arguments:
      - '@ds_encryption.service.cipher'
      - '@annotation_reader'
