services:
    ds_camunda.service.process_definition:
        parent: ds_bpm.service
        class: '%ds_camunda.service.process_definition.class%'

    ds_camunda.service.process_instance:
        parent: ds_bpm.service
        class: '%ds_camunda.service.process_instance.class%'

    ds_camunda.service.task:
        parent: ds_bpm.service
        class: '%ds_camunda.service.task.class%'
