services:
    ds_camunda.service:
        abstract: true
        arguments:
            - '@ds_camunda.http.client'

    ds_camunda.service.process_definition:
        parent: ds_camunda.service
        class: '%ds_camunda.service.process_definition.class%'

    ds_camunda.service.process_instance:
        parent: ds_camunda.service
        class: '%ds_camunda.service.process_instance.class%'

    ds_camunda.service.task:
        parent: ds_camunda.service
        class: '%ds_camunda.service.task.class%'
