parameters:
    ds_discovery.cache.default.class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    ds_discovery.client.class: GuzzleHttp\Client
    ds_discovery.service.discovery.class: Ds\Component\Discovery\Service\DiscoveryService
