services:
  ds_discovery.client:
    class: '%ds_discovery.client.class%'

  ds_discovery.service.discovery:
    class: '%ds_discovery.service.discovery.class%'
    arguments:
      - '@ds_discovery.client'
      - '%discovery_host%'
      - '@ds_discovery.cache.default'
