services:
  ds_api.service.authentication.health:
    parent: ds_api.service
    class: '%ds_api.service.authentication.health.class%'
    tags:
      - { name: ds_api.service, alias: authentication.health }

  ds_api.service.authentication.config:
    parent: ds_api.service
    class: '%ds_api.service.authentication.config.class%'
    tags:
      - { name: ds_api.service, alias: authentication.config }

  ds_api.service.authentication.access:
    parent: ds_api.service
    class: '%ds_api.service.authentication.access.class%'
    tags:
      - { name: ds_api.service, alias: authentication.access }

  ds_api.service.authentication.permission:
    parent: ds_api.service
    class: '%ds_api.service.authentication.permission.class%'
    tags:
      - { name: ds_api.service, alias: authentication.permission }

  ds_api.service.authentication.user:
    parent: ds_api.service
    class: '%ds_api.service.authentication.user.class%'
    tags:
      - { name: ds_api.service, alias: authentication.user }
