services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Api\Service\Cms\HealthService:
    class: Ds\Component\Api\Service\HealthService
    tags:
      - { name: ds_api.service, alias: cms.health }

  Ds\Component\Api\Service\Cms\ConfigService:
    class: Ds\Component\Api\Service\ConfigService
    tags:
      - { name: ds_api.service, alias: cms.config }

  Ds\Component\Api\Service\Cms\AccessService:
    class: Ds\Component\Api\Service\AccessService
    tags:
      - { name: ds_api.service, alias: cms.access }
