services:
  ds_api.service.forms.health:
    parent: ds_api.service
    class: '%ds_api.service.forms.health.class%'
    tags:
      - { name: ds_api.service, alias: forms.health }

  ds_api.service.forms.config:
    parent: ds_api.service
    class: '%ds_api.service.forms.config.class%'
    tags:
      - { name: ds_api.service, alias: forms.config }

  ds_api.service.forms.access:
    parent: ds_api.service
    class: '%ds_api.service.forms.access.class%'
    tags:
      - { name: ds_api.service, alias: forms.access }

  ds_api.service.forms.permission:
    parent: ds_api.service
    class: '%ds_api.service.forms.permission.class%'
    tags:
      - { name: ds_api.service, alias: forms.permission }
