services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Api\Service\Forms\HealthService:
    class: Ds\Component\Api\Service\HealthService
    tags:
      - { name: ds_api.service, alias: forms.health }

  Ds\Component\Api\Service\Forms\ConfigService:
    class: Ds\Component\Api\Service\ConfigService
    tags:
      - { name: ds_api.service, alias: forms.config }

  Ds\Component\Api\Service\Forms\AccessService:
    class: Ds\Component\Api\Service\AccessService
    tags:
      - { name: ds_api.service, alias: forms.access }
