services:
  ds_api.service.records.health:
    parent: ds_api.service
    class: '%ds_api.service.records.health.class%'
    tags:
      - { name: ds_api.service, alias: records.health }

  ds_api.service.records.config:
    parent: ds_api.service
    class: '%ds_api.service.records.config.class%'
    tags:
      - { name: ds_api.service, alias: records.config }

  ds_api.service.records.access:
    parent: ds_api.service
    class: '%ds_api.service.records.access.class%'
    tags:
      - { name: ds_api.service, alias: records.access }

  ds_api.service.records.permission:
    parent: ds_api.service
    class: '%ds_api.service.records.permission.class%'
    tags:
      - { name: ds_api.service, alias: records.permission }
