services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Api\Service\Services\HealthService:
    class: Ds\Component\Api\Service\HealthService
    tags:
      - { name: ds_api.service, alias: services.health }

  Ds\Component\Api\Service\Services\ConfigService:
    class: Ds\Component\Api\Service\ConfigService
    tags:
      - { name: ds_api.service, alias: services.config }

  Ds\Component\Api\Service\Services\AccessService:
    class: Ds\Component\Api\Service\AccessService
    tags:
      - { name: ds_api.service, alias: services.access }
