services:
  ds_acl.filter.access.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        assignee: exact
        assigneeUuid: exact
    tags:
      - { name: api_platform.filter, id: ds_acl.access.search }

  ds_acl.filter.access.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: ds_acl.access.date }
