ds_config:
  configs:
    - { key: ds_api.user.username,        encrypt: false,  title: ds_api.configs.user.username       }
    - { key: ds_api.user.password,        encrypt: true,   title: ds_api.configs.user.password       }
    - { key: ds_api.user.uuid,            encrypt: false,  title: ds_api.configs.user.uuid           }
    - { key: ds_api.user.roles,           encrypt: false,  title: ds_api.configs.user.roles          }
    - { key: ds_api.user.identity.roles,  encrypt: false,  title: ds_api.configs.user.identity.roles }
    - { key: ds_api.user.identity.type,   encrypt: false,  title: ds_api.configs.user.identity.type  }
    - { key: ds_api.user.identity.uuid,   encrypt: false,  title: ds_api.configs.user.identity.uuid  }
    - { key: ds_api.user.tenant,          encrypt: false,  title: ds_api.configs.user.tenant         }
