services:
    ds_api.service.identities.health:
        parent: ds_api.service
        class: '%ds_api.service.identities.health.class%'
        tags:
            - { name: ds_api.service, alias: identities.health }

    ds_api.service.identities.config:
        parent: ds_api.service
        class: '%ds_api.service.identities.config.class%'
        tags:
            - { name: ds_api.service, alias: identities.config }

    ds_api.service.identities.access:
        parent: ds_api.service
        class: '%ds_api.service.identities.access.class%'
        tags:
            - { name: ds_api.service, alias: identities.access }

    ds_api.service.identities.permission:
        parent: ds_api.service
        class: '%ds_api.service.identities.permission.class%'
        tags:
            - { name: ds_api.service, alias: identities.permission }

    ds_api.service.identities.anonymous:
        parent: ds_api.service
        class: '%ds_api.service.identities.anonymous.class%'
        tags:
            - { name: ds_api.service, alias: identities.anonymous }

    ds_api.service.identities.anonymous_persona:
        parent: ds_api.service
        class: '%ds_api.service.identities.anonymous_persona.class%'
        tags:
            - { name: ds_api.service, alias: identities.anonymous_persona }

    ds_api.service.identities.individual:
        parent: ds_api.service
        class: '%ds_api.service.identities.individual.class%'
        tags:
            - { name: ds_api.service, alias: identities.individual }

    ds_api.service.identities.individual_persona:
        parent: ds_api.service
        class: '%ds_api.service.identities.individual_persona.class%'
        tags:
            - { name: ds_api.service, alias: identities.individual_persona }

    ds_api.service.identities.organization:
        parent: ds_api.service
        class: '%ds_api.service.identities.organization.class%'
        tags:
            - { name: ds_api.service, alias: identities.organization }

    ds_api.service.identities.organization_persona:
        parent: ds_api.service
        class: '%ds_api.service.identities.organization_persona.class%'
        tags:
            - { name: ds_api.service, alias: identities.organization_persona }

    ds_api.service.identities.staff:
        parent: ds_api.service
        class: '%ds_api.service.identities.staff.class%'
        tags:
            - { name: ds_api.service, alias: identities.staff }

    ds_api.service.identities.staff_persona:
        parent: ds_api.service
        class: '%ds_api.service.identities.staff_persona.class%'
        tags:
            - { name: ds_api.service, alias: identities.staff_persona }

    ds_api.service.identities.system:
        parent: ds_api.service
        class: '%ds_api.service.identities.system.class%'
        tags:
            - { name: ds_api.service, alias: identities.system }
