services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Resolver\:
    resource: ../../{Collection,Controller,Service}

  Ds\Component\Statistic\Controller\:
    resource: ../../Controller
    tags: [controller.service_arguments]
