parameters:
  ds_config.command.config.get.class: Ds\Component\Config\Command\Config\GetCommand
  ds_config.command.config.set.class: Ds\Component\Config\Command\Config\SetCommand
  ds_config.command.parameter.get.class: Ds\Component\Config\Command\Parameter\GetCommand
  ds_config.command.parameter.set.class: Ds\Component\Config\Command\Parameter\SetCommand
  ds_config.entity.config.class: Ds\Component\Config\Entity\Config
  ds_config.entity.parameter.class: Ds\Component\Config\Entity\Parameter
  ds_config.event_listener.entity.config.post_load.class: Ds\Component\Config\EventListener\Entity\Config\PostLoadListener
  ds_config.event_listener.entity.config.serializer.post_flush.class: Ds\Component\Config\EventListener\Entity\Config\Serializer\PostFlushListener
  ds_config.event_listener.entity.config.serializer.post_load.class: Ds\Component\Config\EventListener\Entity\Config\Serializer\PostLoadListener
  ds_config.event_listener.entity.config.serializer.post_update.class: Ds\Component\Config\EventListener\Entity\Config\Serializer\PostUpdateListener
  ds_config.event_listener.entity.config.serializer.pre_flush.class: Ds\Component\Config\EventListener\Entity\Config\Serializer\PreFlushListener
  ds_config.event_listener.entity.config.serializer.pre_update.class: Ds\Component\Config\EventListener\Entity\Config\Serializer\PreUpdateListener
  ds_config.event_listener.entity.parameter.post_load.class: Ds\Component\Config\EventListener\Entity\Parameter\PostLoadListener
  ds_config.event_listener.entity.parameter.serializer.post_flush.class: Ds\Component\Config\EventListener\Entity\Parameter\Serializer\PostFlushListener
  ds_config.event_listener.entity.parameter.serializer.post_load.class: Ds\Component\Config\EventListener\Entity\Parameter\Serializer\PostLoadListener
  ds_config.event_listener.entity.parameter.serializer.post_update.class: Ds\Component\Config\EventListener\Entity\Parameter\Serializer\PostUpdateListener
  ds_config.event_listener.entity.parameter.serializer.pre_flush.class: Ds\Component\Config\EventListener\Entity\Parameter\Serializer\PreFlushListener
  ds_config.event_listener.entity.parameter.serializer.pre_update.class: Ds\Component\Config\EventListener\Entity\Parameter\Serializer\PreUpdateListener
  ds_config.collection.config.class: Ds\Component\Config\Collection\ConfigCollection
  ds_config.collection.parameter.class: Ds\Component\Config\Collection\ParameterCollection
  ds_config.repository.config.class: Ds\Component\Config\Repository\ConfigRepository
  ds_config.repository.parameter.class: Ds\Component\Config\Repository\ParameterRepository
  ds_config.service.config.class: Ds\Component\Config\Service\ConfigService
  ds_config.service.parameter.class: Ds\Component\Config\Service\ParameterService
  ds_config.tenant.unloader.config.class: Ds\Component\Config\Tenant\Unloader\ConfigUnloader
  ds_config.twig.extension.config.class: Ds\Component\Config\Twig\Extension\ConfigExtension
  ds_config.twig.extension.parameter.class: Ds\Component\Config\Twig\Extension\ParameterExtension
