doctrine:
    orm:
        mappings:
            DsAudit:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../vendor/digitalstate/core/src/Ds/Component/Audit/Entity'
                prefix: Ds\Component\Audit\Entity
                alias: DsAudit

ds_security:
    permissions:
        audit:               { attributes: [BROWSE, READ, EDIT, ADD, DELETE], entity:   Ds\Component\Security\Entity\Audit,              title: ds.security.permissions.audit               }
        audit_property:      { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.*,            title: ds.security.permissions.audit.property      }
        audit_id:            { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.id,           title: ds.security.permissions.audit.id            }
        audit_uuid:          { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.uuid,         title: ds.security.permissions.audit.uiid          }
        audit_created_at:    { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.createdAt,    title: ds.security.permissions.audit.created_at    }
        audit_updated_at:    { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.updatedAt,    title: ds.security.permissions.audit.updated_at    }
        audit_owner:         { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.owner,        title: ds.security.permissions.audit.owner         }
        audit_owner_uuid:    { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.ownerUuid,    title: ds.security.permissions.audit.owner_uuid    }
        audit_user_uuid:     { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.userUuid,     title: ds.security.permissions.audit.user_uuid     }
        audit_identity:      { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.identity,     title: ds.security.permissions.audit.identity      }
        audit_identity_uuid: { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.identityUuid, title: ds.security.permissions.audit.identity_uuid }
        audit_action:        { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.action,       title: ds.security.permissions.audit.action        }
        audit_data:          { attributes: [BROWSE, READ, EDIT],              property: Ds\Component\Security\Entity\Audit.data,         title: ds.security.permissions.audit.data          }
