ds_identity_test:
    identities:
        system:
            username: system
            uuid: 85726ec8-7685-4655-ac91-4746ae71c2cc
            roles: [ROLE_SYSTEM]
            identity: System
            identityUuid: aa18b644-a503-49fa-8f53-10f4c1f8e3a1
        staff:
            username: staff
            uuid: da7bde0e-9690-43b3-abbb-043fb61c679a
            roles: [ROLE_STAFF]
            identity: Staff
            identityUuid: e9111144-71fa-4743-91d0-178653d2e385
        organization:
            username: organization
            uuid: 765eaf87-51f9-44f4-8758-c28f380a0855
            roles: [ROLE_ORGANIZATION]
            identity: Organization
            identityUuid: cedcdc35-84a8-4fa1-8cf1-ff8fea926222
        individual:
            username: individual
            uuid: 0bf2117e-56b4-47ae-87cd-88d7a8bfc758
            roles: [ROLE_INDIVIDUAL]
            identity: Individual
            identityUuid: 5da1504c-68a4-4968-a03a-36e6ac39e8f2
        anonymous:
            username: anonymous
            uuid: f9df049a-fe95-405f-ba7c-734f1a0ce558
            roles: [ROLE_ANONYMOUS]
            identity: Anonymous
            identityUuid: ad1a4ee4-b707-4135-b8e9-498286d5830c
