ds_identity_test:
    identities:
        system:
            username: system
            uuid: 9eb213e2-e108-4d4f-ab6b-62d1e50052ae
            roles: [ROLE_SYSTEM]
            identity: System
            identityUuid: 5386e249-8ad0-45f1-a30e-d5a055cc5993

        staff:
            username: staff
            uuid: b4df246d-0307-4bb9-a732-58326c133839
            roles: [ROLE_STAFF]
            identity: Staff
            identityUuid: f8f05002-f00a-4d6d-b21c-3408a8c24991

        organization:
            username: organization
            uuid: 2533b68a-36d3-44b8-a9db-9f88426a9b19
            roles: [ROLE_ORGANIZATION]
            identity: Organization
            identityUuid: 0ac24776-475d-4d82-ad5f-c3cafc420747

        individual:
            username: individual
            uuid: 536f60f4-f357-4dff-8f8f-a6bcfbd6dfb3
            roles: [ROLE_INDIVIDUAL]
            identity: Individual
            identityUuid: 458d54d9-8aa4-417d-a58b-d7f84df909ae

        anonymous:
            username: anonymous
            uuid: cca27a98-8691-4caa-96b5-015fc6068e8b
            roles: [ROLE_ANONYMOUS]
            identity: Anonymous
            identityUuid: c0391d20-2122-4234-838b-521bd716a54c
