services:
  ds_encryption.event_listener.entity.encryptable.abstract:
    class: '%ds_encryption.event_listener.entity.encryptable.abstract.class%'
    abstract:  true
    arguments:
      - '@ds_encryption.service.encryption'

  ds_encryption.event_listener.entity.encryptable.post_flush:
    class: '%ds_encryption.event_listener.entity.encryptable.post_flush.class%'
    parent: ds_encryption.event_listener.entity.encryptable.abstract
    tags:
      - { name: doctrine.event_listener, event: postFlush, priority: 1 }

  ds_encryption.event_listener.entity.encryptable.post_load:
    class: '%ds_encryption.event_listener.entity.encryptable.post_load.class%'
    parent: ds_encryption.event_listener.entity.encryptable.abstract
    tags:
      - { name: doctrine.event_listener, event: postLoad, priority: 1 }

  ds_encryption.event_listener.entity.encryptable.post_update:
    class: '%ds_encryption.event_listener.entity.encryptable.post_update.class%'
    parent: ds_encryption.event_listener.entity.encryptable.abstract
    tags:
      - { name: doctrine.event_listener, event: postUpdate, priority: 1 }

  ds_encryption.event_listener.entity.encryptable.pre_flush:
    class: '%ds_encryption.event_listener.entity.encryptable.pre_flush.class%'
    parent: ds_encryption.event_listener.entity.encryptable.abstract
    tags:
      - { name: doctrine.event_listener, event: preFlush, priority: 0 }

  ds_encryption.event_listener.entity.encryptable.pre_update:
    class: '%ds_encryption.event_listener.entity.encryptable.pre_update.class%'
    parent: ds_encryption.event_listener.entity.encryptable.abstract
    tags:
      - { name: doctrine.event_listener, event: preUpdate, priority: 0 }
