services:
    ds_entity.service.entity:
        class: '%ds_entity.service.entity.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        public: false

    ds_entity.service.sequence:
        class: '%ds_entity.service.sequence.class%'
