parameters:
  ds_tenant.collection.loader.class: Ds\Component\Tenant\Collection\LoaderCollection
  ds_tenant.command.tenant.load.class: Ds\Component\Tenant\Command\Tenant\LoadCommand
  ds_tenant.doctrine.orm.filter.tenant.class: Ds\Component\Tenant\Doctrine\ORM\Filter\TenantFilter
  ds_tenant.event_listener.context.class: Ds\Component\Tenant\EventListener\ContextListener
  ds_tenant.event_listener.tenantable.class: Ds\Component\Tenant\EventListener\TenantableListener
  ds_tenant.event_listener.token.tenant.class: Ds\Component\Tenant\EventListener\Token\TenantListener
  ds_tenant.service.tenant.class: Ds\Component\Tenant\Service\TenantService
