services:
    ds_security.serializer.normalizer.acl:
        decorates: api_platform.serializer.normalizer.item
        class: '%ds_security.serializer.normalizer.acl.class%'
        arguments:
            - '@ds_security.serializer.normalizer.acl.inner'
            - '@security.token_storage'
            - '@ds_security.voter.permission.property'

    ds_security.serializer.jsonld.normalizer.acl:
        decorates: api_platform.jsonld.normalizer.item
        class: '%ds_security.serializer.normalizer.acl.class%'
        arguments:
            - '@ds_security.serializer.jsonld.normalizer.acl.inner'
            - '@security.token_storage'
            - '@ds_security.voter.permission.property'
