services:
    ds_security.serializer.normalizer.permission:
        decorates: api_platform.serializer.normalizer.item
        class: '%ds_security.serializer.normalizer.permission.class%'
        arguments:
            - '@ds_security.serializer.normalizer.permission.inner'
            - '@security.token_storage'
            - '@ds_security.voter.permission.property'

    ds_security.serializer.jsonld.normalizer.permission:
        decorates: api_platform.jsonld.normalizer.item
        class: '%ds_security.serializer.normalizer.permission.class%'
        arguments:
            - '@ds_security.serializer.jsonld.normalizer.permission.inner'
            - '@security.token_storage'
            - '@ds_security.voter.permission.property'
