services:
    ds_security.collection.permission:
        class: Ds\Component\Security\Collection\PermissionCollection

    ds_security.event_listener.token.ip:
        class: Ds\Component\Security\EventListener\Token\IpListener
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.client:
        class: Ds\Component\Security\EventListener\Token\ClientListener
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.uuid:
        class: Ds\Component\Security\EventListener\Token\UuidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.identity:
        class: Ds\Component\Security\EventListener\Token\IdentityListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.modifier:
        class: Ds\Component\Security\EventListener\Token\ModifierListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }
