parameters:
    ds_security.collection.permission.class: Ds\Component\Security\Collection\PermissionCollection
    ds_security.event_listener.token.ip.class: Ds\Component\Security\EventListener\Token\IpListener
    ds_security.event_listener.token.client.class: Ds\Component\Security\EventListener\Token\ClientListener
    ds_security.event_listener.token.uuid.class: Ds\Component\Security\EventListener\Token\UuidListener
    ds_security.event_listener.token.identity.class: Ds\Component\Security\EventListener\Token\IdentityListener
    ds_security.event_listener.token.modifier.class: Ds\Component\Security\EventListener\Token\ModifierListener
    ds_security.doctrine.orm.query_extension.anonymous.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\AnonymousExtension
    ds_security.doctrine.orm.query_extension.individual.class: Ds\Component\Security\Doctrine\ORM\QueryExtension\IndividualExtension

services:
    ds_security.collection.permission:
        class: "%ds_security.collection.permission.class%"

    ds_security.event_listener.token.ip:
        class: "%ds_security.event_listener.token.ip.class%"
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.client:
        class: "%ds_security.event_listener.token.client.class%"
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.uuid:
        class: "%ds_security.event_listener.token.uuid.%"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.identity:
        class: "%ds_security.event_listener.token.identity.class%"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.event_listener.token.modifier:
        class: "%ds_security.event_listener.token.modifier.class%"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onDecoded }

    ds_security.doctrine.orm.query_extension.anonymous:
        class: "%ds_security.doctrine.orm.query_extension.anonymous.class%"
        public: false
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    ds_security.doctrine.orm.query_extension.individual:
        class: "%ds_security.doctrine.orm.query_extension.individual.class%"
        public: false
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }
