services:
  ds_config.command.config.get:
    class: '%ds_config.command.config.get.class%'
    arguments:
      - '@ds_config.service.config'
    tags:
      - { name: console.command }

  ds_config.command.config.set:
    class: '%ds_config.command.config.set.class%'
    arguments:
      - '@ds_config.service.config'
    tags:
      - { name: console.command }

  ds_config.command.parameter.get:
    class: '%ds_config.command.parameter.get.class%'
    arguments:
      - '@ds_config.service.parameter'
    tags:
      - { name: console.command }

  ds_config.command.parameter.set:
    class: '%ds_config.command.parameter.set.class%'
    arguments:
      - '@ds_config.service.parameter'
    tags:
      - { name: console.command }
