services:
    ds_api.http.client:
        class: '%ds_api.http.client.class%'

    ds_api.api:
        class: '%ds_api.api.class%'
        arguments:
            - '@ds_api.http.client'

    ds_api.factory:
        class: '%ds_api.factory.class%'
        arguments:
            - '@ds_api.api'
            - '@ds_config.service.config'
