parameters:
    ds_api.api.class: Ds\Component\Api\Api\Api
    ds_api.client.class: GuzzleHttp\Client
    ds_api.collection.service.class: Ds\Component\Api\Collection\ServiceCollection
    ds_api.resolver.api.class: Ds\Component\Api\Resolver\ApiResolver
    ds_api.service.authentication.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.authentication.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.authentication.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.authentication.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.authentication.user.class: Ds\Component\Api\Service\UserService
    ds_api.service.assets.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.assets.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.assets.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.assets.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.camunda.deployment.class: Ds\Component\Camunda\Service\DeploymentService
    ds_api.service.camunda.process_definition.class: Ds\Component\Camunda\Service\ProcessDefinitionService
    ds_api.service.camunda.process_instance.class: Ds\Component\Camunda\Service\ProcessInstanceService
    ds_api.service.camunda.task.class: Ds\Component\Camunda\Service\TaskService
    ds_api.service.camunda.task.variable.class: Ds\Component\Camunda\Service\Task\VariableService
    ds_api.service.camunda.tenant.class: Ds\Component\Camunda\Service\TenantService
    ds_api.service.cases.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.cases.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.cases.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.cases.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.cms.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.cms.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.cms.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.cms.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.formio.authentication.class: Ds\Component\Formio\Service\AuthenticationService
    ds_api.service.formio.project.class: Ds\Component\Formio\Service\ProjectService
    ds_api.service.formio.form.class: Ds\Component\Formio\Service\FormService
    ds_api.service.formio.submission.class: Ds\Component\Formio\Service\SubmissionService
    ds_api.service.formio.user.class: Ds\Component\Formio\Service\UserService
    ds_api.service.formio.role.class: Ds\Component\Formio\Service\RoleService
    ds_api.service.identities.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.identities.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.identities.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.identities.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.identities.anonymous.class: Ds\Component\Api\Service\AnonymousService
    ds_api.service.identities.anonymous_persona.class: Ds\Component\Api\Service\AnonymousPersonaService
    ds_api.service.identities.individual.class: Ds\Component\Api\Service\IndividualService
    ds_api.service.identities.individual_persona.class: Ds\Component\Api\Service\IndividualPersonaService
    ds_api.service.identities.organization.class: Ds\Component\Api\Service\OrganizationService
    ds_api.service.identities.organization_persona.class: Ds\Component\Api\Service\OrganizationPersonaService
    ds_api.service.identities.staff.class: Ds\Component\Api\Service\StaffService
    ds_api.service.identities.staff_persona.class: Ds\Component\Api\Service\StaffPersonaService
    ds_api.service.identities.system.class: Ds\Component\Api\Service\SystemService
    ds_api.service.records.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.records.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.records.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.records.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.services.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.services.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.services.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.services.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.service.tasks.health.class: Ds\Component\Api\Service\HealthService
    ds_api.service.tasks.config.class: Ds\Component\Api\Service\ConfigService
    ds_api.service.tasks.access.class: Ds\Component\Api\Service\AccessService
    ds_api.service.tasks.permission.class: Ds\Component\Api\Service\PermissionService
    ds_api.tenant.initializer.config.class: Ds\Component\Api\Tenant\Initializer\ConfigInitializer
