services:
  ds_api.tenant.initializer.config:
    class: '%ds_api.tenant.initializer.config.class%'
    arguments:
      - '@ds_config.service.config'
    tags:
      - { name: ds_tenant.initializer }
