services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Debug\Controller\:
    resource: ../../Controller
    public: true
    tags: [controller.service_arguments]
