services:
  ds_audit.event_listener.entity:
    class: '%ds_audit.event_listener.entity.class%'
    arguments:
      - '@service_container'
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }
