security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  providers:
    ds_system:
      memory:
        users:
          '%system_user%':
              password: '%system_password%'
              roles: ROLE_SYSTEM
