services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Metadata\:
    resource: ../../{Fixture,Repository,Service}

  Ds\Component\Metadata\Fixture\:
    resource: ../../Fixture
    tags: [doctrine.fixture.orm]

  Ds\Component\Metadata\Repository\MetadataRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Ds\Component\Metadata\Entity\Metadata
