services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ds\Component\Query\:
    resource: ../../{Controller}

  Ds\Component\Query\Controller\:
    resource: ../../Controller
    tags: [controller.service_arguments]
