services:
  ds.tenant.filter.tenant.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
    tags:
      - { name: api_platform.filter, id: ds_tenant.tenant.search }

  ds.tenant.filter.tenant.date:
    parent: api_platform.doctrine.orm.date_filter
    arguments:
      - createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: ds_tenant.tenant.date }

  ds.tenant.filter.tenant.order:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
      - id: ~
        createdAt: ~
        updatedAt: ~
    tags:
      - { name: api_platform.filter, id: ds_tenant.tenant.order }
