parameters:
  ds_tenant.collection.loader.class: Ds\Component\Tenant\Collection\LoaderCollection
  ds_tenant.collection.unloader.class: Ds\Component\Tenant\Collection\UnloaderCollection
  ds_tenant.doctrine.orm.filter.tenant.class: Ds\Component\Tenant\Doctrine\ORM\Filter\TenantFilter
  ds_tenant.entity.tenant.class: Ds\Component\Tenant\Entity\Tenant
  ds_tenant.event_listener.context.class: Ds\Component\Tenant\EventListener\ContextListener
  ds_tenant.event_listener.loader.class: Ds\Component\Tenant\EventListener\LoaderListener
  ds_tenant.event_listener.entity.tenantable.class: Ds\Component\Tenant\EventListener\Entity\TenantableListener
  ds_tenant.event_listener.token.tenant.class: Ds\Component\Tenant\EventListener\Token\TenantListener
  ds_tenant.repository.tenant.class: Ds\Component\Tenant\Repository\TenantRepository
  ds_tenant.service.tenant.class: Ds\Component\Tenant\Service\TenantService
