services:
  ds_security.repository.access:
    class: '%ds_security.repository.access.class%'
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - '%ds_security.entity.access.class%'

  ds_security.repository.permission:
    class: '%ds_security.repository.permission.class%'
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - '%ds_security.entity.permission.class%'
