services:
  ds_api.service.cms.health:
    parent: ds_api.service
    class: '%ds_api.service.cms.health.class%'
    tags:
      - { name: ds_api.service, alias: cms.health }

  ds_api.service.cms.config:
    parent: ds_api.service
    class: '%ds_api.service.cms.config.class%'
    tags:
      - { name: ds_api.service, alias: cms.config }

  ds_api.service.cms.access:
    parent: ds_api.service
    class: '%ds_api.service.cms.access.class%'
    tags:
      - { name: ds_api.service, alias: cms.access }

  ds_api.service.cms.permission:
    parent: ds_api.service
    class: '%ds_api.service.cms.permission.class%'
    tags:
      - { name: ds_api.service, alias: cms.permission }
