services:
    ds_bpm.resolver.context.bpm:
        class: '%ds_bpm.resolver.context.bpm.class%'
        arguments:
            - '@ds_api.factory'
        tags:
            - { name: ds_resolver.resolver, alias: ds.context.bpm }
